import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  headerText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: 'black',
    marginLeft: 20,
    marginTop: 17,
  },

  arrow: {
    width: 35,
    height: 35, 
    marginLeft: 26,
    marginTop: 20,
  },

  line: {
    borderBottomColor: "#ccc",
    borderBottomWidth: 2,
    width: "90%",
    alignSelf: "center",
    marginVertical: 15,
  },

  container: {
    flex: 1,
    backgroundColor: "#EEF3F8FF",
    padding: 15,
    marginTop: 25,
  },
  storeHeader: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FAF7F0FF",
    borderRadius: 58,
    padding: 10,
    marginBottom: 15,
    shadowColor: "#000000FF",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  storeIcon: {
    width: 55,
    height: 55,
    borderRadius: 40,
  },
  storeName: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#111111FF",
    marginLeft: 10,
  },
  starIcon: {
    width: 16,
    height: 16,
  },
  sectionTitle: {
    fontWeight: "bold",
    color: "#111111FF",
    fontSize: 14,
    marginBottom: 6,
  },
  salesBox: {
    backgroundColor: "#FAF7F0",
    borderRadius: 15,
    paddingVertical: 20,
    borderWidth: 8,
    borderColor: "#91CAFFFF",
    marginBottom: 15,
    shadowColor: "#000000FF",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
  },
  salesGroup: {
    marginLeft: -20,
  },
  salesRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 30,
    marginVertical: 8,
  },
  bottomRow: {
    width: "45%",
    marginLeft: 32,
    justifyContent: "space-between",
  },
  salesItem: {
    alignItems: "center",
    width: 70,
  },
  salesNumberBox: {
    width: 40,
    height: 40,
    borderWidth: 0.5,
    borderColor: "#000000FF",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
    backgroundColor: "#FFFFFFFF",
  },
  salesNumber: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111111FF",
  },
  salesLabel: {
    fontSize: 12,
    color: "#333333FF",
    textAlign: "center",
  },
  productBox: {
    backgroundColor: "#FAF7F0",
    borderRadius: 15,
    padding: 10,
    borderWidth: 8,
    borderColor: "#FFEB91",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
    shadowColor: "#000000FF",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
  },
  productLeft: {
    flex: 1,
    paddingRight: 8,
  },
  productRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  productLabel: {
    color: "#111111FF",
    fontSize: 13,
    fontWeight: "bold",
  },
  productZero: {
    color: "#111111FF",
    fontSize: 13,
    marginLeft: 3,
  },
  productRightSide: {
    flexDirection: "row",
    alignItems: "center",
  },
  productZeroAligned: {
    color: "#111111FF",
    fontSize: 13,
    textAlign: "right",
  },
  warningIcon: {
    width: 22,
    height: 22,
    tintColor: "#BF130AFF",
  },
  verticalLine: {
    width: 1.5,
    height: "90%",
    backgroundColor: "#CCCCCCFF",
    marginHorizontal: 10,
  },
  productRight: {
    alignItems: "center",
    width: 120,
  },
  topSelling: {
    fontWeight: "bold",
    fontSize: 13,
    color: "#1A73E8FF",
    marginBottom: 5,
    textDecorationLine: "underline",
  },
  emptyImageBox: {
    width: 80,
    height: 80,
    borderColor: "#FFEB91",
    borderWidth: 2,
    borderRadius: 10,
    marginBottom: 5,
  },
  productName: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#111111FF",
  },
  productAmount: {
    fontSize: 11,
    color: "#333333FF",
  },
  metricsBox: {
    backgroundColor: "#FAF7F0",
    borderRadius: 15,
    padding: 10,
    borderWidth: 10,
    borderColor: "#FAF7F0FF",
    marginBottom: 20,
    shadowColor: "#000000FF",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
  },
  metricsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 4,
  },
  metricItem: {
    width: 55,
    height: 55,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  metricNumber: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111111FF",
  },
  metricLabelsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 8,
  },
  metricLabelBox: {
    alignItems: "center",
    width: 70,
  },
  metricLabelBold: {
    fontSize: 11,
    color: "#111111FF",
    fontWeight: "bold",
    textAlign: "center",
  },
  metricsSeparator: {
    height: 1,
    backgroundColor: "#CCCCCCFF",
    marginVertical: 8,
  },
  revenueLabel: {
    fontWeight: "bold",
    color: "#111111FF",
    fontSize: 13,
    marginLeft: 5,
    marginBottom: 8,
  },
  nativeChartContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  nativeChartBars: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    height: 140,
    paddingHorizontal: 6,
  },
  barColumn: {
    alignItems: "center",
    width: (Dimensions.get("window").width - 120) / 6,
  },
  barFill: {
    width: "100%",
    backgroundColor: "#91CAFF",
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
  },
  barLabel: {
    marginTop: 6,
    fontSize: 11,
    color: "#333333FF",
    textAlign: "center",
  },
  rangeButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 10,
  },
  rangeButton: {
    backgroundColor: "#FFFFFFFF",
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  rangeButtonText: {
    color: "#111111FF",
    fontSize: 12,
    fontWeight: "bold",
  },
});
